'use client';
import DocShell, { DocTable, DocList, DocH2, DocH3, DocP, DocStrong, DocEm, DocLink, DocNote } from './DocPage';

export default function AccountManagementPage() {
  return (
    <DocShell
      tag="Legal · Account Policy"
      title="Account Creation & Deletion Privacy Policy"
      subtitle="What We Collect · Why · How It's Protected · Your Rights — DPDP Act 2023 Compliant"
      version="1.0"
      effectiveDate="May 1, 2026"
      lastUpdated="April 2026"
    >
      <DocTable rows={[
        [<DocStrong>Legal Entity</DocStrong>, '[CORPSE ESPORTS PRIVATE LIMITED]'],
        [<DocStrong>Scope</DocStrong>, 'Account creation, sign-up authentication, and account deletion data only'],
        [<DocStrong>Legal Contact</DocStrong>, <DocLink href="mailto:legal@corpsearena.com">legal@corpsearena.com</DocLink>],
        [<DocStrong>Support Contact</DocStrong>, <DocLink href="mailto:support@corpsearena.com">support@corpsearena.com</DocLink>],
      ]} />

      <DocNote><DocEm>This Policy governs data collected exclusively during account creation and deletion. All other platform data practices are governed by the Corpse Full Privacy Policy.</DocEm></DocNote>

      <DocH2>PART I — Introduction & Scope</DocH2>

      <DocH2>1. Who This Policy Applies To</DocH2>
      <DocP>[CORPSE ESPORTS PRIVATE LIMITED] publishes this Account Creation & Deletion Privacy Policy for the Corpse platform. This Policy applies to individuals creating an account, those who begin but don't complete sign-up, Guest Users prior to account creation, and Registered Users initiating or completing account deletion.</DocP>

      <DocH2>2. What This Policy Covers & Excludes</DocH2>
      <DocH3>2.1 Covered</DocH3>
      <DocList items={[
        'Data collected from Guest Users before any account is created',
        'Personal data submitted in the sign-up registration form',
        'Data processed via authentication methods at sign-up (passwordless email, Google, Apple)',
        'Location data collected at the point of registration',
        'Data auto-generated by the Platform when your account is created',
        'The authentication event log entry created at sign-up',
        'Communications directly triggered by sign-up and deletion (Magic Link, deletion verification link)',
        'Data processed during the account deletion request and verification flow',
        'Fate of all data categories after account deletion',
      ]} />
      <DocH3>2.2 Explicitly Excluded</DocH3>
      <DocTable rows={[
        [<DocStrong>Excluded Topic</DocStrong>, <DocStrong>Why Excluded</DocStrong>, <DocStrong>Where Covered</DocStrong>],
        ['OTP, SMS, WhatsApp, promotional communications', 'Post-registration activity', 'Corpse Full Privacy Policy'],
        ['Firebase Analytics data', 'Post-registration platform usage tracking', 'Corpse Full Privacy Policy'],
        ['Razorpay / KYC financial data', 'Only triggered after registration at KYC stage', 'Corpse Full Privacy Policy'],
        ['Tournament, match, squad data', 'Full platform scope — not sign-up or deletion specific', 'Corpse Full Privacy Policy'],
        ['IP address & device model/OS', 'Not collected by the Platform at any stage', 'N/A'],
        ['Browser cookies', 'App uses none; landing page is purely static with zero tracking', 'N/A'],
        ['ELO ranking & match history', 'Generated post-registration through tournament participation', 'Corpse Full Privacy Policy'],
      ]} />

      <DocH2>3. Legal Basis for Processing</DocH2>
      <DocTable rows={[
        [<DocStrong>Legal Basis</DocStrong>, <DocStrong>Data It Applies To</DocStrong>],
        ['Contractual Necessity', 'Name, email, DOB, state, pincode, in-game ID, in-game username — mandatory to deliver account creation. Also applies to deletion verification link processing.'],
        ['Consent', 'Precise latitude and longitude location data — collected only when you explicitly grant location permission. You may decline without affecting account creation.'],
        ['Legitimate Interests', 'Authentication event log (method + timestamp) — collected for security monitoring and fraud prevention.'],
      ]} />

      <DocH2>PART II — Data Collected at Account Creation</DocH2>

      <DocH2>4. Guest User — Before Sign-Up</DocH2>
      <DocList items={[
        'No personal data of any kind is collected or stored during a Guest session.',
        'No registration information, name, email, or location data is recorded.',
        'The session is entirely temporary and stateless — nothing persists once the session ends.',
        'If you proceed to create an account after a Guest session, your Guest session is discarded completely.',
      ]} />

      <DocH2>5. Registration Form Data</DocH2>
      <DocTable rows={[
        [<DocStrong>Field</DocStrong>, <DocStrong>What You Submit</DocStrong>, <DocStrong>Why Mandatory</DocStrong>],
        ['Full legal name', 'Your real full name as it appears on official identification', 'Used to auto-generate your unique, permanent Platform username'],
        ['Email address', 'A valid, active email address you control', 'Primary account identifier across all three authentication methods; delivers the Magic Link'],
        ['Date of birth', 'Your actual date of birth (DD/MM/YYYY)', 'Classifies you as Minor User (under 18) or Standard User, determining your access tier'],
        ['State of residence', 'Your current state of residence within India', 'Region-based ELO ranking and opponent matchmaking grouping'],
        ['Pincode', 'Your current residential pincode', 'Sub-state regional precision for ELO ranking and matchmaking accuracy'],
        ['In-game ID', 'Your unique player ID (e.g., BGMI, Free Fire Max)', 'Ties your Platform account to your in-game identity for tournament registration and result verification'],
        ['In-game username', 'Your display name within the game', 'Used for squad display, match records, and public player profile identification'],
      ]} />
      <DocNote><DocEm>Phone numbers are not collected at any point during account creation. The Platform does not require a phone number for sign-up under any authentication method.</DocEm></DocNote>

      <DocH2>6. Authentication Method Data</DocH2>
      <DocH3>6.1 Passwordless Email (Magic Link)</DocH3>
      <DocTable rows={[
        [<DocStrong>Data Point</DocStrong>, <DocStrong>What Happens to It</DocStrong>],
        ['Email address', 'Stored as your primary account identifier. Used to deliver the Magic Link and all future account-essential communications.'],
        ['Magic Link token', 'A cryptographically secure, single-use token. Valid for 6 hours from issue. Expires and is permanently invalidated immediately upon click or after 6 hours.'],
        ['Link click event', 'Logged as an authentication event — method and timestamp only. No IP address or device data is recorded.'],
        ['Password', 'Not collected. Not stored. The Platform is fully passwordless.'],
      ]} />

      <DocH3>6.2 Google Sign-In</DocH3>
      <DocP>The Platform receives only: your Google account email (used as your Platform identifier) and your Google display name (used to generate your Platform username). No password, recovery details, contacts, or other Google account data is received.</DocP>

      <DocH3>6.3 Apple Sign-In</DocH3>
      <DocP>The Platform receives only: your Apple ID email or relay email (account identifier) and your name as provided by Apple (username basis). Apple only shares the name on first sign-in.</DocP>
      <DocNote><DocStrong>Important: If you use Apple's 'Hide My Email' feature, your Platform account is permanently tied to the relay email Apple provides. Note your relay email address after sign-up.</DocStrong></DocNote>

      <DocH2>PART III — Why We Collect Each Field</DocH2>
      <DocTable rows={[
        [<DocStrong>Data Field</DocStrong>, <DocStrong>Primary Purpose</DocStrong>, <DocStrong>Secondary Purpose</DocStrong>],
        ['Full legal name', 'Auto-generation of unique Platform username', 'KYC identity verification (post-registration)'],
        ['Email address', 'Account identifier and Magic Link delivery', 'Essential account communications; deletion verification'],
        ['Date of birth', 'Minor/Standard user classification', 'Access tier determination; KYC age verification'],
        ['State of residence', 'Regional ELO grouping', 'Opponent matchmaking'],
        ['Pincode', 'Sub-state ELO precision', 'Matchmaking accuracy'],
        ['In-game ID', 'Tournament registration and result verification', 'In-game identity linking'],
        ['In-game username', 'Squad display and public profile', 'Match records'],
        ['Location (lat/long)', 'Hyper-local matchmaking (optional, consent-based)', 'None beyond matchmaking'],
      ]} />

      <DocH2>PART IV — Storage, Protection & Retention</DocH2>
      <DocList items={[
        'All registration data is encrypted in transit using TLS 1.3 or higher.',
        'Data at rest is stored in encrypted databases with access restricted to authorised personnel only.',
        'Magic Link tokens are generated using cryptographically secure random functions and are never logged in plain text.',
        'The deletion verification link is single-use — invalidated immediately upon the user clicking it.',
        'No passwords are ever stored — the Platform is fully passwordless.',
      ]} />

      <DocH2>PART V — Data Collected During Account Deletion</DocH2>
      <DocP>When a user initiates account deletion, the Platform processes: the registered email address (to send the deletion verification link), the deletion verification link token (a single-use, time-limited token), the deletion request timestamp, and the deletion confirmation timestamp. All logged for audit and compliance purposes.</DocP>

      <DocH2>PART VI — Minor Users — Registration Privacy</DocH2>
      <DocP>The Platform classifies users as Minor Users (under 18) or Standard Users at the point of account creation based on the date of birth submitted in the registration form. This classification determines the user's access tier on the Platform.</DocP>

      <DocH2>PART VII — Your Rights</DocH2>
      <DocTable rows={[
        [<DocStrong>Right</DocStrong>, <DocStrong>What It Means in This Context</DocStrong>],
        ['Right to Access', 'You may request confirmation of what registration data we hold about you.'],
        ['Right to Correction', 'You may request correction of inaccurate registration data — including name, DOB, state, pincode, or in-game credentials.'],
        ['Right to Erasure', 'You may request deletion of your account and associated registration data at any time through the account deletion flow.'],
        ['Right to Grievance Redressal', 'You may file a grievance about how your registration or deletion data has been handled.'],
        ['Right to Nominate', 'You may nominate another individual to exercise your data rights in the event of your death or incapacity.'],
      ]} />
      <DocP>To exercise any of your rights, contact: <DocLink href="mailto:legal@corpsearena.com">legal@corpsearena.com</DocLink>. We will respond within 30 days of receipt. Identity verification may be required before processing sensitive requests.</DocP>

      <DocH2>PART VIII — Updates & Contact</DocH2>
      <DocP>We may update this Policy from time to time. When we update this Policy, we will publish the new version with an updated "Last Updated" date. Continued use of the Platform after such changes constitutes acceptance of the updated Policy.</DocP>
      <DocTable rows={[
        [<DocStrong>Contact Type</DocStrong>, <DocStrong>Email</DocStrong>],
        ['Legal & Privacy', <DocLink href="mailto:legal@corpsearena.com">legal@corpsearena.com</DocLink>],
        ['Support', <DocLink href="mailto:support@corpsearena.com">support@corpsearena.com</DocLink>],
      ]} />
    </DocShell>
  );
}
